"""Render a Rampart run as a GitHub pull-request comment (Markdown).

Works from either live ``Finding`` objects (the SDK) or the ``findings`` list in a ``report.json``
(the CLI / the Action), so every surface produces the same comment. The output carries a hidden
marker so the poster can update one sticky comment instead of spamming a new one each run.
"""

from __future__ import annotations

MARKER = "<!-- rampart-report -->"
_SEV_ORDER = ["critical", "high", "medium", "low", "info"]
_SEV_EMOJI = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵", "info": "⚪"}


def _get(obj, key, default=None):
    """Read a field from a dataclass-ish object or a dict."""
    if isinstance(obj, dict):
        return obj.get(key, default)
    return getattr(obj, key, default)


def _location(f) -> str:
    endpoint = _get(f, "endpoint", {}) or {}
    url = _get(endpoint, "url", "") if endpoint else ""
    if url:
        method = _get(endpoint, "method", "") or ""
        return f"{method} {url}".strip()
    affected = _get(f, "affected_code", None)
    if affected:
        file = _get(affected, "file", "")
        line = _get(affected, "start_line", 0)
        if file:
            return f"{file}:{line}" if line else file
    asset = _get(f, "asset", {}) or {}
    return _get(asset, "target", "") or ""


def _normalize(f) -> dict:
    verification = _get(f, "verification", {}) or {}
    tags = _get(f, "tags", []) or []
    return {
        "severity": _get(f, "severity", "info"),
        "title": _get(f, "title", "finding"),
        "vuln_class": _get(f, "vuln_class", ""),
        "cwe": _get(f, "cwe", []) or [],
        "location": _location(f),
        "validated": bool(_get(verification, "validated", False)),
        "state": _get(f, "state", ""),
        "agent": "agent-assessed" in tags,
    }


def _sev_rank(sev: str) -> int:
    order = ["info", "low", "medium", "high", "critical"]
    return order.index(sev) if sev in order else 0


def render_pr_comment(
    findings,
    *,
    application: str = "",
    fail_on: str | None = None,
    report_url: str = "",
    max_rows: int = 30,
) -> str:
    """Return a Markdown PR comment summarizing a run.

    ``findings`` is a list of ``Finding`` objects or report-JSON finding dicts. If ``fail_on`` is
    set, the header shows whether the severity gate passed.
    """
    norm = [_normalize(f) for f in findings]
    confirmed = [f for f in norm if f["validated"] and f["state"] != "Dropped"]
    agent = [f for f in norm if f["agent"] and f["state"] != "Dropped"]
    dropped = [f for f in norm if f["state"] == "Dropped"]

    counts = dict.fromkeys(_SEV_ORDER, 0)
    for f in confirmed:
        counts[f["severity"]] = counts.get(f["severity"], 0) + 1

    gate_line = ""
    if fail_on:
        threshold = _sev_rank(fail_on)
        breached = [f for f in confirmed if _sev_rank(f["severity"]) >= threshold]
        if breached:
            gate_line = f"❌ **Gate failed** — {len(breached)} confirmed finding(s) at or above `{fail_on}`."
        else:
            gate_line = f"✅ **Gate passed** — no confirmed findings at or above `{fail_on}`."

    app = f" for `{application}`" if application else ""
    lines = [MARKER, f"## 🛡️ Rampart security report{app}", ""]
    if gate_line:
        lines += [gate_line, ""]

    if not confirmed:
        lines.append("**No confirmed vulnerabilities.** ✅")
    else:
        badge = " · ".join(f"{_SEV_EMOJI[s]} {counts[s]} {s}" for s in _SEV_ORDER if counts.get(s))
        lines.append(f"**{len(confirmed)} confirmed** — {badge}")
        lines.append("")
        lines.append("| Severity | Finding | Location | CWE |")
        lines.append("|---|---|---|---|")
        ordered = sorted(confirmed, key=lambda f: -_sev_rank(f["severity"]))
        for f in ordered[:max_rows]:
            cwe = ", ".join(f["cwe"][:2]) if f["cwe"] else ""
            loc = f["location"][:80] if f["location"] else ""
            title = str(f["title"]).replace("|", "\\|")[:100]
            lines.append(
                f"| {_SEV_EMOJI.get(f['severity'], '')} {f['severity']} | {title} | `{loc}` | {cwe} |"
            )
        if len(ordered) > max_rows:
            lines.append(f"| … | _{len(ordered) - max_rows} more_ | | |")

    notes = []
    if agent:
        notes.append(f"{len(agent)} agent-assessed (needs human review)")
    if dropped:
        notes.append(f"{len(dropped)} dropped by the false-positive gate")
    if notes:
        lines += ["", "> " + " · ".join(notes) + "."]

    if report_url:
        lines += ["", f"[Full report]({report_url})"]
    lines += ["", f"<sub>Generated by [Rampart](https://github.com/NitinReddy-A/rampart){app}.</sub>"]
    return "\n".join(lines)


def render_from_report(report: dict, **kwargs) -> str:
    """Render from a parsed ``report.json`` dict (its ``findings`` list)."""
    app = kwargs.pop("application", "") or (report.get("engagement", {}) or {}).get("application", "")
    return render_pr_comment(report.get("findings", []) or [], application=app, **kwargs)
